name: do-beacon
version: 'git'
summary: Dynamic DNS using the Digital Ocean API
description: |
  Dynamically update your Digital Ocean DNS records.

grade: stable
confinement: strict

apps:
  do-beacon:
    command: do-beacon
    plugs: [network]

  do-beacond:
    command: do-beacond
    daemon: simple
    plugs: [network]

parts:
  do-beacon:
    source: https://github.com/dboy591/do-beacon.git
    plugin: nodejs
    node-engine: 8.12.0
